const { validate, errors: { CredentialsError } } = require('tasks-util')
const { models: { User } } = require('tasks-data')

module.exports = function (username, password) {
    validate.string(username)
    validate.string.notVoid('username', username)
    validate.string(password)
    validate.string.notVoid('password', password)

    return (async () => {
        const user = await User.findOne({ username, password })

        if (!user) throw new CredentialsError('wrong credentials')

        user.lastAccess = new Date

        await user.save()

        return user.id
    })()
}
/*
module.exports = function(username, password) {
  validate.string(username)
  validate.string.notVoid('username', username)
  validate.string(password)
  validate.string.notVoid('password', password)

  return (async () => {
    const user = await User.findOneAndUpdate({ username, password }, { $set: { lastAccess: new Date} })

    if (!user) throw new CredentialsError('wrong credentials')

    return user.id

  })()
}
*/